// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export { type ClientOptions, Choros as default, Choros } from "./client.js";
export { APIPromise } from "./core/api-promise.js";
export {
	APIConnectionError,
	APIConnectionTimeoutError,
	APIError,
	APIUserAbortError,
	AuthenticationError,
	BadRequestError,
	ConflictError,
	InternalServerError,
	NotFoundError,
	PermissionDeniedError,
	RateLimitError,
	ChorosError,
	UnprocessableEntityError,
} from "./core/error.js";
export { toFile, type Uploadable } from "./core/uploads.js";
export {
	createLocalHostClient,
	type LocalHostAuth,
	type LocalHostAuthProvider,
	type LocalHostClient,
	type LocalHostClientOptions,
} from "./local-host/client.js";
export type {
	Automation,
	AutomationCapabilities,
	AutomationClient,
	AutomationDefinition,
	AutomationDefinitionInput,
	AutomationOccurrence,
	AutomationPage,
	AutomationPreview,
	AutomationRun,
	AutomationRunStatus,
	AutomationSchedule,
	AutomationState,
	ExecutionInput,
	ExecutionReport,
	WorkEvent,
} from "./local-host/client.js";

// Resource classes + their data shapes — bare top-level exports so consumers
// can `import { type Task } from '@choros_sh/sdk'` without going through
// the `Choros` namespace.
export {
	type AgentCreateParams,
	type AgentCreateResult,
	type AgentListParams,
	type AgentListResponse,
	Agents,
	type Host,
	type HostAgentConfig,
	type HostListResponse,
	Hosts,
	type HostWorkspace,
	type Project,
	type ProjectListResponse,
	Projects,
	type PromptTransport,
	type Task,
	type TaskCreateParams,
	type TaskListItem,
	type TaskListParams,
	type TaskListResponse,
	Tasks,
	type TaskUpdateParams,
	type TerminalCloseParams,
	type TerminalCloseResult,
	type TerminalCreateParams,
	type TerminalCreateResult,
	type TerminalListParams,
	type TerminalListResult,
	type TerminalReadParams,
	type TerminalReadResult,
	type TerminalSendParams,
	type TerminalSendResult,
	Terminals,
	type TerminalSummary,
	type Workspace,
	type WorkspaceAgentLaunch,
	type WorkspaceCreateAgentResult,
	type WorkspaceCreateParams,
	type WorkspaceCreateResult,
	type WorkspaceCreateSessionParams,
	type WorkspaceCreateSessionResult,
	type WorkspaceDeleteResult,
	type WorkspaceListParams,
	type WorkspaceListResponse,
	Workspaces,
} from "./resources/index.js";
